// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OperationPackage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReportService {

  /// <summary>Holder for reflection information generated from OperationPackage.proto</summary>
  public static partial class OperationPackageReflection {

    #region Descriptor
    /// <summary>File descriptor for OperationPackage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OperationPackageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZPcGVyYXRpb25QYWNrYWdlLnByb3RvEg1SZXBvcnRTZXJ2aWNlGh9nb29n",
            "bGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvImQKEE9wZXJhdGlvblBhY2th",
            "Z2USDwoHQ3JlYXRlZBgBIAEoAxIVCg1PcGVyYXRpb25OYW1lGAIgASgJEigK",
            "CERhdGFTZXRzGA8gAygLMhYuUmVwb3J0U2VydmljZS5EYXRhU2V0IpgBCgdE",
            "YXRhU2V0EgwKBE5hbWUYASABKAkSKgoHQ29sdW1ucxgCIAMoCzIZLlJlcG9y",
            "dFNlcnZpY2UuQ29sdW1uSW5mbxIgCgRSb3dzGAMgAygLMhIuUmVwb3J0U2Vy",
            "dmljZS5Sb3cSMQoMVmlld1NldHRpbmdzGAQgASgLMhsuUmVwb3J0U2Vydmlj",
            "ZS5WaWV3U2V0dGluZ3MiYgoMVmlld1NldHRpbmdzEh0KFUdyb3VwaW5nQ29s",
            "dW1uTnVtYmVycxgBIAMoBRIzCg1PcmRlclNldHRpbmdzGAIgAygLMhwuUmVw",
            "b3J0U2VydmljZS5PcmRlclNldHRpbmdzIjkKDU9yZGVyU2V0dGluZ3MSFAoM",
            "Q29sdW1uTnVtYmVyGAEgASgFEhIKCkRlc2NlbmRpbmcYAiABKAgiVQoKQ29s",
            "dW1uSW5mbxIMCgROYW1lGAEgASgJEicKBFR5cGUYAiABKA4yGS5SZXBvcnRT",
            "ZXJ2aWNlLlNjYWxhclR5cGUSEAoITnVsbGFibGUYAyABKAgiMgoDUm93EisK",
            "BlZhbHVlcxgBIAMoCzIbLlJlcG9ydFNlcnZpY2UuVmFyaWFudFZhbHVlItMC",
            "CgxWYXJpYW50VmFsdWUSEgoKSW50MzJWYWx1ZRgBIAEoBRITCgtEb3VibGVW",
            "YWx1ZRgCIAEoARISCgpJbnQ2NFZhbHVlGAMgASgDEhEKCUJvb2xWYWx1ZRgE",
            "IAEoCBITCgtTdHJpbmdWYWx1ZRgFIAEoCRISCgpCeXRlc1ZhbHVlGAYgASgM",
            "EhUKDURhdGVUaW1lVmFsdWUYByABKAMSMgoOVGltZVN0YW1wVmFsdWUYCCAB",
            "KAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhIKCkludDE2VmFsdWUY",
            "CSABKAUSEQoJSW50OFZhbHVlGAogASgFEhsKE0RhdGVUaW1lT2Zmc2V0VmFs",
            "dWUYCyABKAMSFQoNVGltZVNwYW5WYWx1ZRgMIAEoAxIUCgxEZWNpbWFsVmFs",
            "dWUYDSABKAESDgoGSXNOdWxsGA8gASgIKr0BCgpTY2FsYXJUeXBlEgsKB1Vu",
            "a25vd24QABIJCgVJbnQzMhABEgoKBkRvdWJsZRACEgkKBUludDY0EAMSCAoE",
            "Qm9vbBAEEgoKBlN0cmluZxAFEgkKBUJ5dGVzEAYSDAoIRGF0ZVRpbWUQBxIN",
            "CglUaW1lU3RhbXAQCBIJCgVJbnQxNhAJEggKBEludDgQChISCg5EYXRlVGlt",
            "ZU9mZnNldBALEgwKCFRpbWVTcGFuEAwSCwoHRGVjaW1hbBANYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ReportService.ScalarType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReportService.OperationPackage), global::ReportService.OperationPackage.Parser, new[]{ "Created", "OperationName", "DataSets" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReportService.DataSet), global::ReportService.DataSet.Parser, new[]{ "Name", "Columns", "Rows", "ViewSettings" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReportService.ViewSettings), global::ReportService.ViewSettings.Parser, new[]{ "GroupingColumnNumbers", "OrderSettings" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReportService.OrderSettings), global::ReportService.OrderSettings.Parser, new[]{ "ColumnNumber", "Descending" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReportService.ColumnInfo), global::ReportService.ColumnInfo.Parser, new[]{ "Name", "Type", "Nullable" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReportService.Row), global::ReportService.Row.Parser, new[]{ "Values" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReportService.VariantValue), global::ReportService.VariantValue.Parser, new[]{ "Int32Value", "DoubleValue", "Int64Value", "BoolValue", "StringValue", "BytesValue", "DateTimeValue", "TimeStampValue", "Int16Value", "Int8Value", "DateTimeOffsetValue", "TimeSpanValue", "DecimalValue", "IsNull" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ScalarType {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    [pbr::OriginalName("Int32")] Int32 = 1,
    [pbr::OriginalName("Double")] Double = 2,
    [pbr::OriginalName("Int64")] Int64 = 3,
    [pbr::OriginalName("Bool")] Bool = 4,
    [pbr::OriginalName("String")] String = 5,
    [pbr::OriginalName("Bytes")] Bytes = 6,
    [pbr::OriginalName("DateTime")] DateTime = 7,
    [pbr::OriginalName("TimeStamp")] TimeStamp = 8,
    [pbr::OriginalName("Int16")] Int16 = 9,
    [pbr::OriginalName("Int8")] Int8 = 10,
    [pbr::OriginalName("DateTimeOffset")] DateTimeOffset = 11,
    [pbr::OriginalName("TimeSpan")] TimeSpan = 12,
    /// <summary>
    ///Can add other if needed.
    /// </summary>
    [pbr::OriginalName("Decimal")] Decimal = 13,
  }

  #endregion

  #region Messages
  public sealed partial class OperationPackage : pb::IMessage<OperationPackage> {
    private static readonly pb::MessageParser<OperationPackage> _parser = new pb::MessageParser<OperationPackage>(() => new OperationPackage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OperationPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReportService.OperationPackageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationPackage(OperationPackage other) : this() {
      created_ = other.created_;
      operationName_ = other.operationName_;
      dataSets_ = other.dataSets_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationPackage Clone() {
      return new OperationPackage(this);
    }

    /// <summary>Field number for the "Created" field.</summary>
    public const int CreatedFieldNumber = 1;
    private long created_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Created {
      get { return created_; }
      set {
        created_ = value;
      }
    }

    /// <summary>Field number for the "OperationName" field.</summary>
    public const int OperationNameFieldNumber = 2;
    private string operationName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OperationName {
      get { return operationName_; }
      set {
        operationName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DataSets" field.</summary>
    public const int DataSetsFieldNumber = 15;
    private static readonly pb::FieldCodec<global::ReportService.DataSet> _repeated_dataSets_codec
        = pb::FieldCodec.ForMessage(122, global::ReportService.DataSet.Parser);
    private readonly pbc::RepeatedField<global::ReportService.DataSet> dataSets_ = new pbc::RepeatedField<global::ReportService.DataSet>();
    /// <summary>
    ///if need to add any no-repeated fields,can place them at 3-14
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ReportService.DataSet> DataSets {
      get { return dataSets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OperationPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OperationPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Created != other.Created) return false;
      if (OperationName != other.OperationName) return false;
      if(!dataSets_.Equals(other.dataSets_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Created != 0L) hash ^= Created.GetHashCode();
      if (OperationName.Length != 0) hash ^= OperationName.GetHashCode();
      hash ^= dataSets_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Created != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Created);
      }
      if (OperationName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OperationName);
      }
      dataSets_.WriteTo(output, _repeated_dataSets_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Created != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Created);
      }
      if (OperationName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OperationName);
      }
      size += dataSets_.CalculateSize(_repeated_dataSets_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OperationPackage other) {
      if (other == null) {
        return;
      }
      if (other.Created != 0L) {
        Created = other.Created;
      }
      if (other.OperationName.Length != 0) {
        OperationName = other.OperationName;
      }
      dataSets_.Add(other.dataSets_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Created = input.ReadInt64();
            break;
          }
          case 18: {
            OperationName = input.ReadString();
            break;
          }
          case 122: {
            dataSets_.AddEntriesFrom(input, _repeated_dataSets_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DataSet : pb::IMessage<DataSet> {
    private static readonly pb::MessageParser<DataSet> _parser = new pb::MessageParser<DataSet>(() => new DataSet());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReportService.OperationPackageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataSet(DataSet other) : this() {
      name_ = other.name_;
      columns_ = other.columns_.Clone();
      rows_ = other.rows_.Clone();
      ViewSettings = other.viewSettings_ != null ? other.ViewSettings.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataSet Clone() {
      return new DataSet(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Columns" field.</summary>
    public const int ColumnsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ReportService.ColumnInfo> _repeated_columns_codec
        = pb::FieldCodec.ForMessage(18, global::ReportService.ColumnInfo.Parser);
    private readonly pbc::RepeatedField<global::ReportService.ColumnInfo> columns_ = new pbc::RepeatedField<global::ReportService.ColumnInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ReportService.ColumnInfo> Columns {
      get { return columns_; }
    }

    /// <summary>Field number for the "Rows" field.</summary>
    public const int RowsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::ReportService.Row> _repeated_rows_codec
        = pb::FieldCodec.ForMessage(26, global::ReportService.Row.Parser);
    private readonly pbc::RepeatedField<global::ReportService.Row> rows_ = new pbc::RepeatedField<global::ReportService.Row>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ReportService.Row> Rows {
      get { return rows_; }
    }

    /// <summary>Field number for the "ViewSettings" field.</summary>
    public const int ViewSettingsFieldNumber = 4;
    private global::ReportService.ViewSettings viewSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ReportService.ViewSettings ViewSettings {
      get { return viewSettings_; }
      set {
        viewSettings_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!columns_.Equals(other.columns_)) return false;
      if(!rows_.Equals(other.rows_)) return false;
      if (!object.Equals(ViewSettings, other.ViewSettings)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= columns_.GetHashCode();
      hash ^= rows_.GetHashCode();
      if (viewSettings_ != null) hash ^= ViewSettings.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      columns_.WriteTo(output, _repeated_columns_codec);
      rows_.WriteTo(output, _repeated_rows_codec);
      if (viewSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ViewSettings);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += columns_.CalculateSize(_repeated_columns_codec);
      size += rows_.CalculateSize(_repeated_rows_codec);
      if (viewSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ViewSettings);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataSet other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      columns_.Add(other.columns_);
      rows_.Add(other.rows_);
      if (other.viewSettings_ != null) {
        if (viewSettings_ == null) {
          viewSettings_ = new global::ReportService.ViewSettings();
        }
        ViewSettings.MergeFrom(other.ViewSettings);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            columns_.AddEntriesFrom(input, _repeated_columns_codec);
            break;
          }
          case 26: {
            rows_.AddEntriesFrom(input, _repeated_rows_codec);
            break;
          }
          case 34: {
            if (viewSettings_ == null) {
              viewSettings_ = new global::ReportService.ViewSettings();
            }
            input.ReadMessage(viewSettings_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ViewSettings : pb::IMessage<ViewSettings> {
    private static readonly pb::MessageParser<ViewSettings> _parser = new pb::MessageParser<ViewSettings>(() => new ViewSettings());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ViewSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReportService.OperationPackageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ViewSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ViewSettings(ViewSettings other) : this() {
      groupingColumnNumbers_ = other.groupingColumnNumbers_.Clone();
      orderSettings_ = other.orderSettings_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ViewSettings Clone() {
      return new ViewSettings(this);
    }

    /// <summary>Field number for the "GroupingColumnNumbers" field.</summary>
    public const int GroupingColumnNumbersFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_groupingColumnNumbers_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> groupingColumnNumbers_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> GroupingColumnNumbers {
      get { return groupingColumnNumbers_; }
    }

    /// <summary>Field number for the "OrderSettings" field.</summary>
    public const int OrderSettingsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ReportService.OrderSettings> _repeated_orderSettings_codec
        = pb::FieldCodec.ForMessage(18, global::ReportService.OrderSettings.Parser);
    private readonly pbc::RepeatedField<global::ReportService.OrderSettings> orderSettings_ = new pbc::RepeatedField<global::ReportService.OrderSettings>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ReportService.OrderSettings> OrderSettings {
      get { return orderSettings_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ViewSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ViewSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!groupingColumnNumbers_.Equals(other.groupingColumnNumbers_)) return false;
      if(!orderSettings_.Equals(other.orderSettings_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= groupingColumnNumbers_.GetHashCode();
      hash ^= orderSettings_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      groupingColumnNumbers_.WriteTo(output, _repeated_groupingColumnNumbers_codec);
      orderSettings_.WriteTo(output, _repeated_orderSettings_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += groupingColumnNumbers_.CalculateSize(_repeated_groupingColumnNumbers_codec);
      size += orderSettings_.CalculateSize(_repeated_orderSettings_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ViewSettings other) {
      if (other == null) {
        return;
      }
      groupingColumnNumbers_.Add(other.groupingColumnNumbers_);
      orderSettings_.Add(other.orderSettings_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            groupingColumnNumbers_.AddEntriesFrom(input, _repeated_groupingColumnNumbers_codec);
            break;
          }
          case 18: {
            orderSettings_.AddEntriesFrom(input, _repeated_orderSettings_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class OrderSettings : pb::IMessage<OrderSettings> {
    private static readonly pb::MessageParser<OrderSettings> _parser = new pb::MessageParser<OrderSettings>(() => new OrderSettings());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReportService.OperationPackageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderSettings(OrderSettings other) : this() {
      columnNumber_ = other.columnNumber_;
      descending_ = other.descending_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderSettings Clone() {
      return new OrderSettings(this);
    }

    /// <summary>Field number for the "ColumnNumber" field.</summary>
    public const int ColumnNumberFieldNumber = 1;
    private int columnNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ColumnNumber {
      get { return columnNumber_; }
      set {
        columnNumber_ = value;
      }
    }

    /// <summary>Field number for the "Descending" field.</summary>
    public const int DescendingFieldNumber = 2;
    private bool descending_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Descending {
      get { return descending_; }
      set {
        descending_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ColumnNumber != other.ColumnNumber) return false;
      if (Descending != other.Descending) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ColumnNumber != 0) hash ^= ColumnNumber.GetHashCode();
      if (Descending != false) hash ^= Descending.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ColumnNumber != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ColumnNumber);
      }
      if (Descending != false) {
        output.WriteRawTag(16);
        output.WriteBool(Descending);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ColumnNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ColumnNumber);
      }
      if (Descending != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderSettings other) {
      if (other == null) {
        return;
      }
      if (other.ColumnNumber != 0) {
        ColumnNumber = other.ColumnNumber;
      }
      if (other.Descending != false) {
        Descending = other.Descending;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ColumnNumber = input.ReadInt32();
            break;
          }
          case 16: {
            Descending = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ColumnInfo : pb::IMessage<ColumnInfo> {
    private static readonly pb::MessageParser<ColumnInfo> _parser = new pb::MessageParser<ColumnInfo>(() => new ColumnInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ColumnInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReportService.OperationPackageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ColumnInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ColumnInfo(ColumnInfo other) : this() {
      name_ = other.name_;
      type_ = other.type_;
      nullable_ = other.nullable_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ColumnInfo Clone() {
      return new ColumnInfo(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::ReportService.ScalarType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ReportService.ScalarType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Nullable" field.</summary>
    public const int NullableFieldNumber = 3;
    private bool nullable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Nullable {
      get { return nullable_; }
      set {
        nullable_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ColumnInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ColumnInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (Nullable != other.Nullable) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Nullable != false) hash ^= Nullable.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Nullable != false) {
        output.WriteRawTag(24);
        output.WriteBool(Nullable);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Nullable != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ColumnInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Nullable != false) {
        Nullable = other.Nullable;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            type_ = (global::ReportService.ScalarType) input.ReadEnum();
            break;
          }
          case 24: {
            Nullable = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Row : pb::IMessage<Row> {
    private static readonly pb::MessageParser<Row> _parser = new pb::MessageParser<Row>(() => new Row());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Row> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReportService.OperationPackageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Row() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Row(Row other) : this() {
      values_ = other.values_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Row Clone() {
      return new Row(this);
    }

    /// <summary>Field number for the "Values" field.</summary>
    public const int ValuesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReportService.VariantValue> _repeated_values_codec
        = pb::FieldCodec.ForMessage(10, global::ReportService.VariantValue.Parser);
    private readonly pbc::RepeatedField<global::ReportService.VariantValue> values_ = new pbc::RepeatedField<global::ReportService.VariantValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ReportService.VariantValue> Values {
      get { return values_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Row);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Row other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!values_.Equals(other.values_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= values_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      values_.WriteTo(output, _repeated_values_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += values_.CalculateSize(_repeated_values_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Row other) {
      if (other == null) {
        return;
      }
      values_.Add(other.values_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            values_.AddEntriesFrom(input, _repeated_values_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class VariantValue : pb::IMessage<VariantValue> {
    private static readonly pb::MessageParser<VariantValue> _parser = new pb::MessageParser<VariantValue>(() => new VariantValue());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VariantValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReportService.OperationPackageReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VariantValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VariantValue(VariantValue other) : this() {
      int32Value_ = other.int32Value_;
      doubleValue_ = other.doubleValue_;
      int64Value_ = other.int64Value_;
      boolValue_ = other.boolValue_;
      stringValue_ = other.stringValue_;
      bytesValue_ = other.bytesValue_;
      dateTimeValue_ = other.dateTimeValue_;
      TimeStampValue = other.timeStampValue_ != null ? other.TimeStampValue.Clone() : null;
      int16Value_ = other.int16Value_;
      int8Value_ = other.int8Value_;
      dateTimeOffsetValue_ = other.dateTimeOffsetValue_;
      timeSpanValue_ = other.timeSpanValue_;
      decimalValue_ = other.decimalValue_;
      isNull_ = other.isNull_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VariantValue Clone() {
      return new VariantValue(this);
    }

    /// <summary>Field number for the "Int32Value" field.</summary>
    public const int Int32ValueFieldNumber = 1;
    private int int32Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Int32Value {
      get { return int32Value_; }
      set {
        int32Value_ = value;
      }
    }

    /// <summary>Field number for the "DoubleValue" field.</summary>
    public const int DoubleValueFieldNumber = 2;
    private double doubleValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double DoubleValue {
      get { return doubleValue_; }
      set {
        doubleValue_ = value;
      }
    }

    /// <summary>Field number for the "Int64Value" field.</summary>
    public const int Int64ValueFieldNumber = 3;
    private long int64Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Int64Value {
      get { return int64Value_; }
      set {
        int64Value_ = value;
      }
    }

    /// <summary>Field number for the "BoolValue" field.</summary>
    public const int BoolValueFieldNumber = 4;
    private bool boolValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BoolValue {
      get { return boolValue_; }
      set {
        boolValue_ = value;
      }
    }

    /// <summary>Field number for the "StringValue" field.</summary>
    public const int StringValueFieldNumber = 5;
    private string stringValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringValue {
      get { return stringValue_; }
      set {
        stringValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BytesValue" field.</summary>
    public const int BytesValueFieldNumber = 6;
    private pb::ByteString bytesValue_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString BytesValue {
      get { return bytesValue_; }
      set {
        bytesValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DateTimeValue" field.</summary>
    public const int DateTimeValueFieldNumber = 7;
    private long dateTimeValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DateTimeValue {
      get { return dateTimeValue_; }
      set {
        dateTimeValue_ = value;
      }
    }

    /// <summary>Field number for the "TimeStampValue" field.</summary>
    public const int TimeStampValueFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeStampValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeStampValue {
      get { return timeStampValue_; }
      set {
        timeStampValue_ = value;
      }
    }

    /// <summary>Field number for the "Int16Value" field.</summary>
    public const int Int16ValueFieldNumber = 9;
    private int int16Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Int16Value {
      get { return int16Value_; }
      set {
        int16Value_ = value;
      }
    }

    /// <summary>Field number for the "Int8Value" field.</summary>
    public const int Int8ValueFieldNumber = 10;
    private int int8Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Int8Value {
      get { return int8Value_; }
      set {
        int8Value_ = value;
      }
    }

    /// <summary>Field number for the "DateTimeOffsetValue" field.</summary>
    public const int DateTimeOffsetValueFieldNumber = 11;
    private long dateTimeOffsetValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DateTimeOffsetValue {
      get { return dateTimeOffsetValue_; }
      set {
        dateTimeOffsetValue_ = value;
      }
    }

    /// <summary>Field number for the "TimeSpanValue" field.</summary>
    public const int TimeSpanValueFieldNumber = 12;
    private long timeSpanValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimeSpanValue {
      get { return timeSpanValue_; }
      set {
        timeSpanValue_ = value;
      }
    }

    /// <summary>Field number for the "DecimalValue" field.</summary>
    public const int DecimalValueFieldNumber = 13;
    private double decimalValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double DecimalValue {
      get { return decimalValue_; }
      set {
        decimalValue_ = value;
      }
    }

    /// <summary>Field number for the "IsNull" field.</summary>
    public const int IsNullFieldNumber = 15;
    private bool isNull_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsNull {
      get { return isNull_; }
      set {
        isNull_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VariantValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VariantValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Int32Value != other.Int32Value) return false;
      if (DoubleValue != other.DoubleValue) return false;
      if (Int64Value != other.Int64Value) return false;
      if (BoolValue != other.BoolValue) return false;
      if (StringValue != other.StringValue) return false;
      if (BytesValue != other.BytesValue) return false;
      if (DateTimeValue != other.DateTimeValue) return false;
      if (!object.Equals(TimeStampValue, other.TimeStampValue)) return false;
      if (Int16Value != other.Int16Value) return false;
      if (Int8Value != other.Int8Value) return false;
      if (DateTimeOffsetValue != other.DateTimeOffsetValue) return false;
      if (TimeSpanValue != other.TimeSpanValue) return false;
      if (DecimalValue != other.DecimalValue) return false;
      if (IsNull != other.IsNull) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Int32Value != 0) hash ^= Int32Value.GetHashCode();
      if (DoubleValue != 0D) hash ^= DoubleValue.GetHashCode();
      if (Int64Value != 0L) hash ^= Int64Value.GetHashCode();
      if (BoolValue != false) hash ^= BoolValue.GetHashCode();
      if (StringValue.Length != 0) hash ^= StringValue.GetHashCode();
      if (BytesValue.Length != 0) hash ^= BytesValue.GetHashCode();
      if (DateTimeValue != 0L) hash ^= DateTimeValue.GetHashCode();
      if (timeStampValue_ != null) hash ^= TimeStampValue.GetHashCode();
      if (Int16Value != 0) hash ^= Int16Value.GetHashCode();
      if (Int8Value != 0) hash ^= Int8Value.GetHashCode();
      if (DateTimeOffsetValue != 0L) hash ^= DateTimeOffsetValue.GetHashCode();
      if (TimeSpanValue != 0L) hash ^= TimeSpanValue.GetHashCode();
      if (DecimalValue != 0D) hash ^= DecimalValue.GetHashCode();
      if (IsNull != false) hash ^= IsNull.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Int32Value != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Value);
      }
      if (DoubleValue != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(DoubleValue);
      }
      if (Int64Value != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Int64Value);
      }
      if (BoolValue != false) {
        output.WriteRawTag(32);
        output.WriteBool(BoolValue);
      }
      if (StringValue.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(StringValue);
      }
      if (BytesValue.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(BytesValue);
      }
      if (DateTimeValue != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(DateTimeValue);
      }
      if (timeStampValue_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(TimeStampValue);
      }
      if (Int16Value != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Int16Value);
      }
      if (Int8Value != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Int8Value);
      }
      if (DateTimeOffsetValue != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(DateTimeOffsetValue);
      }
      if (TimeSpanValue != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(TimeSpanValue);
      }
      if (DecimalValue != 0D) {
        output.WriteRawTag(105);
        output.WriteDouble(DecimalValue);
      }
      if (IsNull != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsNull);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Int32Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int32Value);
      }
      if (DoubleValue != 0D) {
        size += 1 + 8;
      }
      if (Int64Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Value);
      }
      if (BoolValue != false) {
        size += 1 + 1;
      }
      if (StringValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue);
      }
      if (BytesValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BytesValue);
      }
      if (DateTimeValue != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DateTimeValue);
      }
      if (timeStampValue_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStampValue);
      }
      if (Int16Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int16Value);
      }
      if (Int8Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int8Value);
      }
      if (DateTimeOffsetValue != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DateTimeOffsetValue);
      }
      if (TimeSpanValue != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeSpanValue);
      }
      if (DecimalValue != 0D) {
        size += 1 + 8;
      }
      if (IsNull != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VariantValue other) {
      if (other == null) {
        return;
      }
      if (other.Int32Value != 0) {
        Int32Value = other.Int32Value;
      }
      if (other.DoubleValue != 0D) {
        DoubleValue = other.DoubleValue;
      }
      if (other.Int64Value != 0L) {
        Int64Value = other.Int64Value;
      }
      if (other.BoolValue != false) {
        BoolValue = other.BoolValue;
      }
      if (other.StringValue.Length != 0) {
        StringValue = other.StringValue;
      }
      if (other.BytesValue.Length != 0) {
        BytesValue = other.BytesValue;
      }
      if (other.DateTimeValue != 0L) {
        DateTimeValue = other.DateTimeValue;
      }
      if (other.timeStampValue_ != null) {
        if (timeStampValue_ == null) {
          timeStampValue_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeStampValue.MergeFrom(other.TimeStampValue);
      }
      if (other.Int16Value != 0) {
        Int16Value = other.Int16Value;
      }
      if (other.Int8Value != 0) {
        Int8Value = other.Int8Value;
      }
      if (other.DateTimeOffsetValue != 0L) {
        DateTimeOffsetValue = other.DateTimeOffsetValue;
      }
      if (other.TimeSpanValue != 0L) {
        TimeSpanValue = other.TimeSpanValue;
      }
      if (other.DecimalValue != 0D) {
        DecimalValue = other.DecimalValue;
      }
      if (other.IsNull != false) {
        IsNull = other.IsNull;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Int32Value = input.ReadInt32();
            break;
          }
          case 17: {
            DoubleValue = input.ReadDouble();
            break;
          }
          case 24: {
            Int64Value = input.ReadInt64();
            break;
          }
          case 32: {
            BoolValue = input.ReadBool();
            break;
          }
          case 42: {
            StringValue = input.ReadString();
            break;
          }
          case 50: {
            BytesValue = input.ReadBytes();
            break;
          }
          case 56: {
            DateTimeValue = input.ReadInt64();
            break;
          }
          case 66: {
            if (timeStampValue_ == null) {
              timeStampValue_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(timeStampValue_);
            break;
          }
          case 72: {
            Int16Value = input.ReadInt32();
            break;
          }
          case 80: {
            Int8Value = input.ReadInt32();
            break;
          }
          case 88: {
            DateTimeOffsetValue = input.ReadInt64();
            break;
          }
          case 96: {
            TimeSpanValue = input.ReadInt64();
            break;
          }
          case 105: {
            DecimalValue = input.ReadDouble();
            break;
          }
          case 120: {
            IsNull = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
